version: '3.7'

services:
  mariadb:
    ports:
      - '${MYSQL_PORT}:3306'
  php:
    volumes:
      - './apps/symfony-website/:/usr/src/app'
  nginx:
    volumes:
      - './apps/symfony-website/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
